mode: train
data:
  train_paths: ['data/libri_train_1h/data_list_sorted.json',
                'data/libri_train_9h/data_list_sorted.json']
  dev_paths: ['data/libri_dev/data_list_sorted.json']
  text:
    mode: character
    vocab: data/libri_train_1h/vocab_char.txt
accum_steps : 8
fs_step: 500
ss_step: 10000
ts_step: 20000
enable_sch: False
model:
  name: las_asr
  extractor:
    name: fbank
    train: false
    feature: hidden_states
  encoder:
    hid_dim: 256
    n_layers: 3
    module: GRU
    bidirectional: true
    dropout: 0.2
  optim:
    algo: Adam
    kwargs:
      lr: 0.001
#   specaugment:
#     freq_mask_range: [0, 27]
#     freq_mask_num: 2
#     time_mask_range: [0, 100]
#     time_mask_num: 2
#     time_mask_max: 1.0
#     time_warp_w: 80

hparam:
  train_batch_size: 6
  val_batch_size: 5
  accum_grad: 1
#   grad_clip: 5000
  njobs: 4
  pin_memory: true

checkpoint_callbacks:
  monitor: val_wer
  mode: min
  save_top_k: 5  # -1: all ckpts will be saved

trainer:
  max_epochs: 500
  max_steps: 8000
  check_val_every_n_epoch: 1
  gpus: 1
  precision: 16
  logger: true
  log_every_n_steps: 5
  flush_logs_every_n_steps: 5
  default_root_dir: model/ctc_libri-10h_char
  deterministic: true
